# Generated by Django 3.1 on 2023-02-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('rate', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('adult_rate', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('trailer', models.TextField(blank=True, null=True)),
                ('main_video', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('account_address', models.TextField(blank=True, null=True)),
                ('created_nft', models.TextField(blank=True, null=True)),
                ('date_of_joining', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('collections', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiledetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
